# Módulos {.unnumbered}

## Objetivo do Curso:

O curso visa qualificar a tomada de decisão e a avaliação das políticas públicas de saúde, em especial as relacionadas à vigilância em saúde, por meio da formação em serviço de trabalhadores do Sistema Único de Saúde do ES sobre ferramentas de análise de dados e estatística e da realização de estudos e análises de dados epidemiológicos sob demanda relacionadas ao projeto.

### Público alvo:

Trabalhadores do Sistema Único de Saúde do Espírito Santo

### Metodologia

O curso é oferecido sob a forma de Educação a Distância, de forma assíncrona, com encontros de tutoria, sendo mediado por material didático e por encontros síncronos quinzenais.

### Recursos

Serão utilizados vídeos, textos e scripts.

### Atividades

As atividades avaliativas são coerentes com os conteúdos propostos nos vídeos e textos. Para isso, serão utilizadas a avaliação processual realizada por meio de questionários compostos por questões de múltipla escolha.

## Ementa

Neste curso você aprenderá:

##### Módulo Boas-Vindas

Conceitos de inferência estatística; principais modelos de probabilidade; estimação pontual e intervalar.

##### Módulo I

Testes de hipóteses para parâmetros; modelos de regressão linear simples e múltipla para dados quantitativos e qualitativos; seleção de modelos via métodos stepwise.

##### Módulo II

Coeficiente R2 e Teste F; dados supervisionados e não supervisionados. Exemplos reais;

##### Módulo III

explorando técnicas de Machine Learning; modelos de Machine Learning para dados supervisionados: Regressão Logística, KNN e Florestas Aleatórias;

##### Módulo IV

modelos de Machine Learning para dados não supervisionados: técnicas multivariadas de dados (análise de cluster e análise fatorial); métricas de ajustes de modelos: acurácia, sensibilidade, especificidade e índice kappa;

##### Módulo V

elaboração de projeto de análise exploratória de dados; uso de scripts e pacotes no R; Comunicando com visualização de dados e storytelling.

Carga Horária Total: 60h

Todo o processo é guiado com carga teórica e prática por intermédio da linguagem R.

------------------------------------------------------------------------
